/*
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * \'embedding\' is provided but \'vectorIndex\' is not provided.
 */
export type KdbAiTableCreateResponseBodyData = {
    error?: string | undefined;
};

/**
 * \'embedding\' is provided but \'vectorIndex\' is not provided.
 */
export class KdbAiTableCreateResponseBody extends Error {
    error?: string | undefined;

    /** The original data that was passed to this error instance. */
    data$: KdbAiTableCreateResponseBodyData;

    constructor(err: KdbAiTableCreateResponseBodyData) {
        const message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : `API error occurred: ${JSON.stringify(err)}`;
        super(message);
        this.data$ = err;

        if (err.error != null) {
            this.error = err.error;
        }

        this.name = "KdbAiTableCreateResponseBody";
    }
}

/** @internal */
export const KdbAiTableCreateResponseBody$inboundSchema: z.ZodType<
    KdbAiTableCreateResponseBody,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        error: z.string().optional(),
    })
    .transform((v) => {
        return new KdbAiTableCreateResponseBody(v);
    });

/** @internal */
export type KdbAiTableCreateResponseBody$Outbound = {
    error?: string | undefined;
};

/** @internal */
export const KdbAiTableCreateResponseBody$outboundSchema: z.ZodType<
    KdbAiTableCreateResponseBody$Outbound,
    z.ZodTypeDef,
    KdbAiTableCreateResponseBody
> = z
    .instanceof(KdbAiTableCreateResponseBody)
    .transform((v) => v.data$)
    .pipe(
        z.object({
            error: z.string().optional(),
        })
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace KdbAiTableCreateResponseBody$ {
    /** @deprecated use `KdbAiTableCreateResponseBody$inboundSchema` instead. */
    export const inboundSchema = KdbAiTableCreateResponseBody$inboundSchema;
    /** @deprecated use `KdbAiTableCreateResponseBody$outboundSchema` instead. */
    export const outboundSchema = KdbAiTableCreateResponseBody$outboundSchema;
    /** @deprecated use `KdbAiTableCreateResponseBody$Outbound` instead. */
    export type Outbound = KdbAiTableCreateResponseBody$Outbound;
}
