workflowVersion: 1.0.0
sources:
    kx-OAS:
        inputs:
            - location: ./openapi.yaml
        overlays:
            - location: ./overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-bar-test/speakeasy-bar-test/kx-oas
targets:
    kx:
        target: typescript
        source: kx-OAS
