/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type KdbAiTrainRawResponse = string | string;

/** @internal */
export const KdbAiTrainRawResponse$inboundSchema: z.ZodType<
    KdbAiTrainRawResponse,
    z.ZodTypeDef,
    unknown
> = z.union([z.string(), z.string()]);

/** @internal */
export type KdbAiTrainRawResponse$Outbound = string | string;

/** @internal */
export const KdbAiTrainRawResponse$outboundSchema: z.ZodType<
    KdbAiTrainRawResponse$Outbound,
    z.ZodTypeDef,
    KdbAiTrainRawResponse
> = z.union([z.string(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace KdbAiTrainRawResponse$ {
    /** @deprecated use `KdbAiTrainRawResponse$inboundSchema` instead. */
    export const inboundSchema = KdbAiTrainRawResponse$inboundSchema;
    /** @deprecated use `KdbAiTrainRawResponse$outboundSchema` instead. */
    export const outboundSchema = KdbAiTrainRawResponse$outboundSchema;
    /** @deprecated use `KdbAiTrainRawResponse$Outbound` instead. */
    export type Outbound = KdbAiTrainRawResponse$Outbound;
}
