/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type KdbAiTableDeleteRequest = {
    name: string;
};

/** @internal */
export const KdbAiTableDeleteRequest$inboundSchema: z.ZodType<
    KdbAiTableDeleteRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    name: z.string(),
});

/** @internal */
export type KdbAiTableDeleteRequest$Outbound = {
    name: string;
};

/** @internal */
export const KdbAiTableDeleteRequest$outboundSchema: z.ZodType<
    KdbAiTableDeleteRequest$Outbound,
    z.ZodTypeDef,
    KdbAiTableDeleteRequest
> = z.object({
    name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace KdbAiTableDeleteRequest$ {
    /** @deprecated use `KdbAiTableDeleteRequest$inboundSchema` instead. */
    export const inboundSchema = KdbAiTableDeleteRequest$inboundSchema;
    /** @deprecated use `KdbAiTableDeleteRequest$outboundSchema` instead. */
    export const outboundSchema = KdbAiTableDeleteRequest$outboundSchema;
    /** @deprecated use `KdbAiTableDeleteRequest$Outbound` instead. */
    export type Outbound = KdbAiTableDeleteRequest$Outbound;
}
