/*
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type KdbAiTableCreateRequest = {
    name: string;
    /**
     * An object with table metadata and list of columns
     */
    table: components.Table;
};

/** @internal */
export const KdbAiTableCreateRequest$inboundSchema: z.ZodType<
    KdbAiTableCreateRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        name: z.string(),
        Table: components.Table$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            Table: "table",
        });
    });

/** @internal */
export type KdbAiTableCreateRequest$Outbound = {
    name: string;
    Table: components.Table$Outbound;
};

/** @internal */
export const KdbAiTableCreateRequest$outboundSchema: z.ZodType<
    KdbAiTableCreateRequest$Outbound,
    z.ZodTypeDef,
    KdbAiTableCreateRequest
> = z
    .object({
        name: z.string(),
        table: components.Table$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            table: "Table",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace KdbAiTableCreateRequest$ {
    /** @deprecated use `KdbAiTableCreateRequest$inboundSchema` instead. */
    export const inboundSchema = KdbAiTableCreateRequest$inboundSchema;
    /** @deprecated use `KdbAiTableCreateRequest$outboundSchema` instead. */
    export const outboundSchema = KdbAiTableCreateRequest$outboundSchema;
    /** @deprecated use `KdbAiTableCreateRequest$Outbound` instead. */
    export type Outbound = KdbAiTableCreateRequest$Outbound;
}
