/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type KdbAiTableMetaRequest = {
    name: string;
};

/** @internal */
export const KdbAiTableMetaRequest$inboundSchema: z.ZodType<
    KdbAiTableMetaRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    name: z.string(),
});

/** @internal */
export type KdbAiTableMetaRequest$Outbound = {
    name: string;
};

/** @internal */
export const KdbAiTableMetaRequest$outboundSchema: z.ZodType<
    KdbAiTableMetaRequest$Outbound,
    z.ZodTypeDef,
    KdbAiTableMetaRequest
> = z.object({
    name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace KdbAiTableMetaRequest$ {
    /** @deprecated use `KdbAiTableMetaRequest$inboundSchema` instead. */
    export const inboundSchema = KdbAiTableMetaRequest$inboundSchema;
    /** @deprecated use `KdbAiTableMetaRequest$outboundSchema` instead. */
    export const outboundSchema = KdbAiTableMetaRequest$outboundSchema;
    /** @deprecated use `KdbAiTableMetaRequest$Outbound` instead. */
    export type Outbound = KdbAiTableMetaRequest$Outbound;
}
