/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type KdbAiTrainJsonResponse = string | string;

/** @internal */
export const KdbAiTrainJsonResponse$inboundSchema: z.ZodType<
    KdbAiTrainJsonResponse,
    z.ZodTypeDef,
    unknown
> = z.union([z.string(), z.string()]);

/** @internal */
export type KdbAiTrainJsonResponse$Outbound = string | string;

/** @internal */
export const KdbAiTrainJsonResponse$outboundSchema: z.ZodType<
    KdbAiTrainJsonResponse$Outbound,
    z.ZodTypeDef,
    KdbAiTrainJsonResponse
> = z.union([z.string(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace KdbAiTrainJsonResponse$ {
    /** @deprecated use `KdbAiTrainJsonResponse$inboundSchema` instead. */
    export const inboundSchema = KdbAiTrainJsonResponse$inboundSchema;
    /** @deprecated use `KdbAiTrainJsonResponse$outboundSchema` instead. */
    export const outboundSchema = KdbAiTrainJsonResponse$outboundSchema;
    /** @deprecated use `KdbAiTrainJsonResponse$Outbound` instead. */
    export type Outbound = KdbAiTrainJsonResponse$Outbound;
}
