/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

/**
 * Distance metric.
 */
export const DistanceMetric = {
    L2: "L2",
    Ip: "IP",
    Cs: "CS",
} as const;
/**
 * Distance metric.
 */
export type DistanceMetric = ClosedEnum<typeof DistanceMetric>;

/** @internal */
export const DistanceMetric$inboundSchema: z.ZodNativeEnum<typeof DistanceMetric> =
    z.nativeEnum(DistanceMetric);

/** @internal */
export const DistanceMetric$outboundSchema: z.ZodNativeEnum<typeof DistanceMetric> =
    DistanceMetric$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DistanceMetric$ {
    /** @deprecated use `DistanceMetric$inboundSchema` instead. */
    export const inboundSchema = DistanceMetric$inboundSchema;
    /** @deprecated use `DistanceMetric$outboundSchema` instead. */
    export const outboundSchema = DistanceMetric$outboundSchema;
}
