/*
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

import {
    RCHeader,
    RCHeader$inboundSchema,
    RCHeader$Outbound,
    RCHeader$outboundSchema,
} from "./rcheader.js";
import * as z from "zod";

export type Payload = {};

export type RCResponse = {
    header?: RCHeader | undefined;
    payload?: Payload | undefined;
};

/** @internal */
export const Payload$inboundSchema: z.ZodType<Payload, z.ZodTypeDef, unknown> = z.object({});

/** @internal */
export type Payload$Outbound = {};

/** @internal */
export const Payload$outboundSchema: z.ZodType<Payload$Outbound, z.ZodTypeDef, Payload> = z.object(
    {}
);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Payload$ {
    /** @deprecated use `Payload$inboundSchema` instead. */
    export const inboundSchema = Payload$inboundSchema;
    /** @deprecated use `Payload$outboundSchema` instead. */
    export const outboundSchema = Payload$outboundSchema;
    /** @deprecated use `Payload$Outbound` instead. */
    export type Outbound = Payload$Outbound;
}

/** @internal */
export const RCResponse$inboundSchema: z.ZodType<RCResponse, z.ZodTypeDef, unknown> = z.object({
    header: RCHeader$inboundSchema.optional(),
    payload: z.lazy(() => Payload$inboundSchema).optional(),
});

/** @internal */
export type RCResponse$Outbound = {
    header?: RCHeader$Outbound | undefined;
    payload?: Payload$Outbound | undefined;
};

/** @internal */
export const RCResponse$outboundSchema: z.ZodType<RCResponse$Outbound, z.ZodTypeDef, RCResponse> =
    z.object({
        header: RCHeader$outboundSchema.optional(),
        payload: z.lazy(() => Payload$outboundSchema).optional(),
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RCResponse$ {
    /** @deprecated use `RCResponse$inboundSchema` instead. */
    export const inboundSchema = RCResponse$inboundSchema;
    /** @deprecated use `RCResponse$outboundSchema` instead. */
    export const outboundSchema = RCResponse$outboundSchema;
    /** @deprecated use `RCResponse$Outbound` instead. */
    export type Outbound = RCResponse$Outbound;
}
