/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type SuccessResponse = {
    message?: string | undefined;
};

/** @internal */
export const SuccessResponse$inboundSchema: z.ZodType<SuccessResponse, z.ZodTypeDef, unknown> =
    z.object({
        message: z.string().optional(),
    });

/** @internal */
export type SuccessResponse$Outbound = {
    message?: string | undefined;
};

/** @internal */
export const SuccessResponse$outboundSchema: z.ZodType<
    SuccessResponse$Outbound,
    z.ZodTypeDef,
    SuccessResponse
> = z.object({
    message: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SuccessResponse$ {
    /** @deprecated use `SuccessResponse$inboundSchema` instead. */
    export const inboundSchema = SuccessResponse$inboundSchema;
    /** @deprecated use `SuccessResponse$outboundSchema` instead. */
    export const outboundSchema = SuccessResponse$outboundSchema;
    /** @deprecated use `SuccessResponse$Outbound` instead. */
    export type Outbound = SuccessResponse$Outbound;
}
